-- supporting testfile; belongs to 'cl_spec.lua'

describe("Tests the busted command-line options (--dryrun)", function()

  describe("test body", function()
    it("a test", function()
      error("test should not execute")
    end)
  end)

  describe("setup", function()
    setup(function()
      error("setup should not be executed")
    end)
    it("test", function() end)
  end)

  describe("setup", function()
    setup(function()
      error("setup should not be executed")
    end)
    describe("nested context", function()
      it("test", function() end)
    end)
  end)

  describe("teardown", function()
    teardown(function()
      error("teardown should not be executed")
    end)
    it("test", function() end)
  end)

  describe("teardown", function()
    teardown(function()
      error("teardown should not be executed")
    end)
    describe("nested context", function()
      it("test", function() end)
    end)
  end)

  describe("before_each", function()
    before_each(function()
      error("before_each should not be executed")
    end)
    it("test", function() end)
  end)

  describe("before_each", function()
    before_each(function()
      error("before_each should not be executed")
    end)
    describe("nested context", function()
      it("test", function() end)
    end)
  end)

  describe("after_each", function()
    after_each(function()
      error("after_each should not be executed")
    end)
    it("test", function() end)
  end)

  describe("after_each", function()
    after_each(function()
      error("after_each should not be executed")
    end)
    describe("nested context", function()
      it("test", function() end)
    end)
  end)

end)
